export const dummyTransactions = [
  {
    id: "tx-1051",
    userId: "u-1001",
    userName: "Shachar Hasson",
    amount: 4200,
    date: "2026-02-06T14:33",
    description: "Wire Transfer",
    suspicious: false,
    isPending: false,
    status: "approved",
  },
  {
    id: "tx-1052",
    userId: "u-1001",
    userName: "Shachar Hasson",
    amount: 16.89,
    date: "2026-02-07T17:44",
    description: "Restaurant - Starbucks",
    suspicious: false,
    isPending: false,
    status: "rejected",
  },
  {
    id: "tx-1053",
    userId: "u-1002",
    userName: "Nilli Etzel",
    amount: 4999.5,
    date: "2026-02-05T09:16",
    description: "Wire Transfer",
    suspicious: true,
    isPending: true,
    status: "pending",
  },
  {
    id: "tx-1054",
    userId: "u-1002",
    userName: "Nilli Etzel",
    amount: 340.2,
    date: "2026-02-08T11:24",
    description: "Online Purchase - Amazon",
    suspicious: false,
    isPending: true,
    status: "pending",
  },
];
